name: CI - Run Pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install uv tool
      run: python -m pip install uv

    - name: Install project dependencies
      run: python -m uv install

    - name: Run tests
      run: pytest